config/routes.rb
Rails.application.routes.draw do
  get 'bookmarks/create'
  get 'bookmarks/destroy'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :profiles
  # Defines the root path route ("/")
  # root "articles#index"
  resources :articles
  resources :articles do
    member do
      post 'like'
      post 'unlike'
    end
  end
  root 'articles#index'
  resources :bookmarks, only: [:create, :destroy]
  resources :articles do
    member do
      get :my_article_view
      get :my_article
      post :bookmark
      delete :unbookmark
    end
  end
  resources :profiles do
    member do
      get :show_user_profile
    end
  end
  # post 'follow', to: 'profiles#follow' 
  # resources :profiles do
  #   member do
  #     post 'follow/:user_id', to: 'profiles#follow', as: 'follow'
  #     delete 'unfollow/:user_id', to: 'profiles#unfollow', as: 'unfollow'
  #   end
  # end  
 
  get '/sports', to: 'sports#index'
  get '/politics', to: 'politics#index'
  get '/technologyes', to: 'technologyes#index'
  get '/healths', to: 'healths#index'
  get '/governments', to: 'governments#index'
  get '/fashiones', to: 'fashiones#index'
  get '/businesses', to: 'businesses#index'
  get '/automobiles', to: 'automobiles#index'

  resources :articles do
    resources :ratings, only: [:create, :update, :destroy]
  end

  
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many_attached :file , dependent: :destroy
  mount_uploader :file, FileUploader
  #has_many :comments, dependent: :destroy
  has_many :article_views
  
  validates :title, presence: true
  validates :content, presence: true
  
  enum :article_type , {sport: 0, politics: 1, government: 2, education: 3, health: 4, environment: 5, economy: 6, business: 7, tech: 8, entertainment: 9, automobile: 10}  
  has_many :likes, dependent: :destroy
  has_many :bookmarks, dependent: :destroy 
  has_many :ratings, dependent: :destroy

  


  def average_rating
    if ratings.count > 0
      ratings.average(:value).round(1)
    else
      "No ratings yet"
    end
  end

  # has_many :follows, foreign_key: :followed_id, dependent: :destroy
  # has_many :followers, through: :follows, source: :follower
  
end

app/models/article_view.rb
class ArticleView < ApplicationRecord
  belongs_to :article
  belongs_to :user
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy, :bookmark, :unbookmark]

  def index
    @articles = Article.all
    @q = Article.ransack(params[:q])
    @articles = @q.result(distinct: true).order(created_at: :desc).page(params[:page]).per(10)
    if user_signed_in? 
    @profile = current_user.profile
    @articles_today = Article.where("DATE(created_at) = ?", Date.today)
    @articles_likes = Article.left_joins(:likes).group(:id).order('COUNT(likes.id) DESC')
    @sport_articles = Article.where(article_type: 'sport')
    @politics_articles = Article.where(article_type: 'politics')
    @technology_articles = Article.where(article_type: 'tech')
    @government_articles = Article.where(article_type: 'government')
    @health_articles = Article.where(article_type: 'health')
    @business_articles = Article.where(article_type: 'business')
    @automobile_articles = Article.where(article_type: 'automobile')
    @education_articles = Article.where(article_type: 'education')
    @entertainment_articles = Article.where(article_type: 'entertainment')
    @environment_articles = Article.where(article_type: 'environment')
    @economy_articles = Article.where(article_type: 'economy')
    end
  end

  def show
    # @article = Article.find(params[:id])
    # @rating = current_user.ratings.build
    # @following = current_user.followers(@user)
    @article_view = @article.article_views.find_or_create_by(user: current_user)
    @article_view.increment!(:view_count)
  end

  
  def new
    @article = current_user.articles.build
    #@article.article_categories.build.build_category
  end

  def edit
  end

  def create
    @article = current_user.articles.build(article_params)
    if @article.save
      redirect_to @article, notice: 'Article was successfully created.'
    else
      render :new
    end
  end

  def update
    if @article.update(article_params)
      redirect_to @article, notice: 'Article was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_url, notice: 'Article was successfully destroyed.'
  end

  def like
    @article = Article.find(params[:id])
    current_user.likes.create(article: @article)
    redirect_to @article
  end

  def unlike
    @article = Article.find(params[:id])
    current_user.likes.where(article: @article).destroy_all
    redirect_to root_path
  end

  def bookmark
    current_user.bookmarks.create(article: @article)
    redirect_to root_path
  end

  def unbookmark
    current_user.bookmarks.find_by(article: @article).destroy
    redirect_to @article
  end

  def my_article
    @my_article = current_user.articles
    @profile = current_user.profile 
  end

  def my_article_view
    @article = Article.find(params[:id])
    @article_view = @article.article_views.find_or_create_by(user: current_user)
    @article_view.increment!(:view_count)
    @article_views_by_day = @article.article_views.group_by_day(:created_at).count
    @article_views_by_month = @article.article_views.group_by_month(:created_at).count
    @article_views_data = @article.article_views.group_by_day(:created_at).count
  end

  def article_view 
    
  end
private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :content, :article_type,:user_id,:file)
  end
end
  

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_header.html.erb
<!-- Font Awesome -->
<link
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
  rel="stylesheet"
/>
<!-- Google Fonts -->
<link
  href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
  rel="stylesheet"
/>
<!-- MDB -->
<link
  href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.3.1/mdb.min.css"
  rel="stylesheet"
/>




<!-- Navbar -->
<nav class="navbar fixed-top navbar-expand-lg navbar-dark" style="background:#0146BF;">
  <!-- Container wrapper -->
  <div class="container-fluid">
    <!-- Toggle button -->
    <button
      class="navbar-toggler"
      type="button"
      data-mdb-toggle="collapse"
      data-mdb-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <i class="fas fa-bars"></i>
    </button>

    <!-- Collapsible wrapper -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <!-- Navbar brand -->
      <a class="navbar-brand mt-2 mt-lg-0" href="#">
        <img
          src="https://mdbcdn.b-cdn.net/img/logo/mdb-transaprent-noshadows.webp"
          height="15"
          alt="MDB Logo"
          loading="lazy"
        />
      </a>
      <!-- Left links -->
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">  
        <i class="fa-solid fa-home ml-3" style="color:#fff; margin-top:11px;"></i>
        <li class="nav-item">
          <a class="nav-link active" href="#" style="text-decoration:none;">Home</a>
        </li>
        <i class="fa-solid fa-gear ml-3" style="color:#fff; margin-top:11px;"></i>
        <li class="nav-item">
          <a class="nav-link active" href="#" style="text-decoration:none;">Setting</a>
        </li>
        <i class="fa-solid fa-eject ml-3" style="color:#fff; margin-top:11px;"></i>
        <li class="nav-item">
          <a class="nav-link active" href="#"style="text-decoration:none;" >About</a>
        </li>
        <i class="fa-solid fa-bookmark ml-3" style="color:#fff; margin-top:11px;"></i>
        <li class="nav-item">
          <a class="nav-link active" href="#" style="text-decoration:none;">Bokmarked</a>
        </li>
        <i class="fa-regular fa-newspaper ml-3" style="color:#fff; margin-top:11px;"></i>
        <% if current_user.present?%>
        <li class="nav-item">
          <a style="text-decoration:none;"><%= link_to 'My Article' , my_article_article_path(@articles) , class:'nav-link active' %></a>
        </li>
        <% else %>
        <li class="nav-item">
          <a style="text-decoration:none;"><%= link_to 'My Article' , new_user_session_path , class:'nav-link active' %></a>
        </li>
        <% end%>

        <% if current_user.present?%>
        <i class="fa fa-user ml-3" style="color:#fff; margin-top:11px;" ></i>
        <% if @profile.present? %>
           <li class="nav-item">
            <span class=""></span><%= link_to 'Profile',@profile , class:'nav-link active' , style:'text-decoration:none;' %>
           </li>
        <% else %>
            <li class="nav-item ">
            <span class=""></span><%= link_to 'Profile' , new_profile_path , class:'nav-link active' , style:'text-decoration:none;' %>
            </li>
        <% end %>
        <% else %>
            <i class="fa fa-user ml-3" style="color:#fff; margin-top:11px;" ></i>
            <li class="nav-item">
            <span class=""></span><%= link_to 'Profile',new_user_session_path , class:'nav-link active' , style:'text-decoration:none;' %>
           </li>
        <% end %>    
      </ul>
      <!-- Left links -->
    </div>
    <!-- Collapsible wrapper -->

    <!-- Right elements -->
    <div class="d-flex align-items-center">
      <!-- Icon -->
      <% if user_signed_in? %>
      <i class="fa-solid fa-right-from-bracket" style="color:#fff;"></i>
      <a class="text-reset me-3" >
         <%= button_to 'Logout', destroy_user_session_path, class:"" ,style:'background:#0146BF; color:fff; border:none; box-shadow: rgba(0, 0, 0, 0.35) 0px 0px 0px;', method: :delete %>
      <% else %>
         <i class="fa-solid fa-right-to-bracket" style="color:#fff;"></i>
         <%= button_to 'Login', new_user_session_path, class:"" , style:'background:#0146BF; color:fff; border:none; box-shadow: rgba(0, 0, 0, 0.35) 0px 0px 0px;'%>
      <% end %>
      </a>

      <!-- Notifications -->
      <div class="dropdown">
        <a
          class="text-reset me-3 dropdown-toggle hidden-arrow"
          href="#"
          id="navbarDropdownMenuLink"
          role="button"
          data-mdb-toggle="dropdown"
          aria-expanded="false"
        >
          <i class="fas fa-bell" style="color:#fff;"></i>
          <span class="badge rounded-pill badge-notification bg-danger">1</span>
        </a>
        <ul
          class="dropdown-menu dropdown-menu-end"
          aria-labelledby="navbarDropdownMenuLink"
        >
          <li>
            <a class="dropdown-item" href="#">Some news</a>
          </li>
          <li>
            <a class="dropdown-item" href="#">Another news</a>
          </li>
          <li>
            <a class="dropdown-item" href="#">Something else here</a>
          </li>
        </ul>
      </div>
      <!-- Avatar -->
    </div>
    <!-- Right elements -->
  </div>
  <!-- Container wrapper -->
</nav>
<!-- Navbar -->


<!-- MDB -->
<script
  type="text/javascript"
  src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.3.1/mdb.min.js"
></script>

app/views/articles/my_article.html.erb
<!-- Font Awesome -->
<link
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
  rel="stylesheet"
/>
<!-- Google Fonts -->
<link
  href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
  rel="stylesheet"
/>
<!-- MDB -->
<link
  href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.3.1/mdb.min.css"
  rel="stylesheet"
/>


<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
  font-family: "Lato", sans-serif;
}

.sidenav {
  height: 100%;
  width: 215px;
  position: fixed;
  z-index: 1;
  top: 0;
  left: 0;
  background-color: #fff;
  border: solid 1px #D0D0D0;
  overflow-x: hidden;
  padding-top: 8px;
  margin-top:54px;
}


.main {
  margin-left: 210px; /* Same as the width of the sidenav */
}

@media screen and (max-height: 450px) {
  .sidenav {padding-top: 15px;}
  .sidenav a {font-size: 18px;}
}

.nav-item:hover{
    background:#EFF0F0;
}

.nav-link:focus{
    color:#0146BF;
}

.card:hover{
  box-shadow: rgba(0, 0, 0, 0.35) 0px 5px 15px;
}
</style>
</head>
<body>

<div class="sidenav">
 <div class="pb-2" style="border-bottom: 1px solid #DEDDDD;">
  <div class="btn text-center ml-3 pl-5 pr-5 mb-1 mt-1" style="background-color:#0146BF;"> 
   <i class="fa-solid fa-plus" style="color:#fff; font-size:17px;">&nbsp
   </i><%= link_to ' New Post' , new_article_path  , style:' text-decoration:none; color:#fff; '%>
  </div>    
 </div>
  <div class="" id="ex1" role="tablist">
  <div class="nav-item  mt-4 pb-2 pt-2" role="presentation">
    <a class="nav-link active ml-4" id="ex1-tab-1" data-mdb-toggle="tab" href="#ex1-tabs-1" role="tab" aria-controls="ex1-tabs-1" aria-selected="true" style="text-decoration:none; font-size:20px; color:;"><i class="fa-solid fa-newspaper" style="font-size:20px;"></i>&nbsp Posts</a>
  </div>
  <div class="nav-item mt-3 pb-2 pt-2" role="presentation">
    <a
      class="nav-link ml-4"
      id="ex1-tab-2"
      data-mdb-toggle="tab"
      href="#ex1-tabs-2"
      role="tab"
      aria-controls="ex1-tabs-2"
      aria-selected="false"
      style="text-decoration:none; font-size:20px; color:;"
      ><i class="fa-solid fa-chart-column"></i>&nbsp Stats</a
    >
  </div>
  <div class="nav-item mt-3 pb-2 pt-2" role="presentation">
    <a
      class="nav-link ml-4"
      id="ex1-tab-3"
      data-mdb-toggle="tab"
      href="#ex1-tabs-3"
      role="tab"
      aria-controls="ex1-tabs-3"
      aria-selected="false"
      style="text-decoration:none; font-size:20px;color:;"
      ><i class="fa-solid fa-message"></i>&nbsp Comments</a
    >
  </div>
  <div class="nav-item mt-3 pb-2 pt-2" role="presentation">
    <a
      class="nav-link ml-4"
      id="ex1-tab-4"
      data-mdb-toggle="tab"
      href="#ex1-tabs-4"
      role="tab"
      aria-controls="ex1-tabs-4"
      aria-selected="false"
      style="text-decoration:none; font-size:20px;color:;"
      ><i class="fa-sharp fa-solid fa-file-lines"></i></i>&nbsp Pages</a
    >
  </div>
  <div class="nav-item mt-3 pb-2 pt-2" role="presentation">
    <a
      class="nav-link ml-4"
      id="ex1-tab-5"
      data-mdb-toggle="tab"
      href="#ex1-tabs-5"
      role="tab"
      aria-controls="ex1-tabs-5"
      aria-selected="false"
      style="text-decoration:none; font-size:20px;color:;"
      ><i class="fa-solid fa-table"></i>&nbsp Layout</a
    >
  </div>
  <div class="nav-item mt-3 pb-2 pt-2" role="presentation">
    <a
      class="nav-link ml-4"
      id="ex1-tab-6"
      data-mdb-toggle="tab"
      href="#ex1-tabs-6"
      role="tab"
      aria-controls="ex1-tabs-6"
      aria-selected="false"
      style="text-decoration:none; font-size:20px;color:;"
      ><i class="fa-solid fa-gear"></i>&nbsp Setting</a
    >
  </div>
  <div class="nav-item mt-3 pb-2 pt-2" role="presentation">
    <a
      class="nav-link ml-4"
      id="ex1-tab-7"
      data-mdb-toggle="tab"
      href="#ex1-tabs-7"
      role="tab"
      aria-controls="ex1-tabs-7"
      aria-selected="false"
      style="text-decoration:none; font-size:20px;color:;"
      ><i class="fa-solid fa-bookmark"></i>&nbsp Reading List</a
    >
  </div>
</div>
</div>

<div class="main">
<!-- Navbar -->
<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light" style="box-shadow: rgba(0, 0, 0, 0.35) 0px 0px 0px; border: solid 1px; border-color:#DEDDDD ; height:55px;">
  <!-- Container wrapper -->
  <div class="container-fluid">
    <!-- Toggle button -->
    <button
      class="navbar-toggler"
      type="button"
      data-mdb-toggle="collapse"
      data-mdb-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <i class="fas fa-bars"></i>
    </button>

    <!-- Collapsible wrapper -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <!-- Navbar brand -->
      <a class="navbar-brand mt-2 mt-lg-0" href="#">
        
      </a>
      <!-- Left links -->
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link text-decoration-none" href="#" style="font-size:30px; color:#0146BF;"><i class="fa-brands fa-slack fa-spin" style="color:#0146BF; font-size:35px;"></i>&nbsp News App </a>
        </li>
        
      </ul>
      <!-- Left links -->
    </div>
    <!-- Collapsible wrapper -->

    <!-- Right elements -->
    <div class="d-flex align-items-center">
      

      <!-- Notifications -->
      <div class="dropdown">
        <a
          class="text-reset me-3 dropdown-toggle hidden-arrow"
          href="#"
          id="navbarDropdownMenuLink"
          role="button"
          data-mdb-toggle="dropdown"
          aria-expanded="false"
        >
          <i class="fas fa-bell"></i>
          <span class="badge rounded-pill badge-notification bg-danger">1</span>
        </a>
        <ul
          class="dropdown-menu dropdown-menu-end"
          aria-labelledby="navbarDropdownMenuLink"
        >
          <li>
            <a class="dropdown-item" href="#">Some news</a>
          </li>
          <li>
            <a class="dropdown-item" href="#">Another news</a>
          </li>
          <li>
            <a class="dropdown-item" href="#">Something else here</a>
          </li>
        </ul>
      </div>
      <!-- Avatar -->
      <div class="dropdown">
        <a
          class="dropdown-toggle d-flex align-items-center hidden-arrow"
          href="#"
          id="navbarDropdownMenuAvatar"
          role="button"
          data-mdb-toggle="dropdown"
          aria-expanded="false"
        >
          <img
            src="https://mdbcdn.b-cdn.net/img/new/avatars/2.webp"
            class="rounded-circle"
            height="25"
            alt="Black and White Portrait of a Man"
            loading="lazy"
          />
        </a>
        <ul
          class="dropdown-menu dropdown-menu-end"
          aria-labelledby="navbarDropdownMenuAvatar"
        >
          <li>
            <a class=""><%= link_to 'My Profile' , @profile , class:'dropdown-item text-decoration-none'%></a>
          </li>
          <li>
            <a class="dropdown-item text-decoration-none" href="#">Settings</a>
          </li>
          <li>
            <a class=""><%= link_to 'Logout', destroy_user_session_path, class:"dropdown-item text-decoration-none" ,style:'', method: :delete %></a>
          </li>
        </ul>
      </div>
    </div>
    <!-- Right elements -->
  </div>
  <!-- Container wrapper -->
</nav><br>
<!-- Navbar -->
<div class="container mt-5">  
<!-- Tabs content -->
<div class="tab-content mt-5" id="ex1-content" style="border:none;">
  <div class="tab-pane fade show active" id="ex1-tabs-1" role="tabpanel" aria-labelledby="ex1-tab-1">
        <nav class="navbar navbar-expand-lg navbar-light bg-light shadow-none">
            <div class="container-fluid">
                <ul class="navbar-nav">
                <!-- Dropdown -->
                    <select class="form-select border-0 shadow-none" aria-label="Default select example" style="width:130px;" >
                    <option selected>All (<%= @my_article.count %>)</option>
                    <option value="1">Published (4)</option>
                    <option value="2">Shaduled (0)</option>
                    <option value="3">Bin (0)</option>
                    </select>
                </ul>
                <div>
                    <i class="fa-solid fa-receipt mr-3 text-primary"></i>
                    <a href="#" class="text-primary text-decoration-none">MANAGE</a> 
                </div>
            </div>
        </nav>
    <% @my_article.each do |article| %>
     <div class="card mb-3" style="max-width:; border: solid 1px #D0D0D0 ; box-shadow: rgba(0, 0, 0, 0.35) 0px 0px 0px;">
        <div class="row g-0">
            <div class="col-md-1">
            <img src="<%= article.file%>" alt="Trendy Pants and Shoes" class="img-fluid rounded mt-3 ml-3 mb-3" style="height:90px; width:90px;"/>
            </div>
            <div class="col ml-4">
            <div class="card-body">
                <p class="card-text" style="font-size:17px;"><b><%= article.title.truncate(110) %></b><i class="fa-solid fa-eye " data-bs-toggle="tooltip"  title="View" style="float:right;"></i><i class="fa-solid fa-trash mr-4" data-bs-toggle="tooltip"  title="Remove this post" style="float:right;"></i><i class="fa-solid fa-tag mr-4" data-bs-toggle="tooltip"  title="Tag Labels" style="float:right;" ></i><i class="fa-solid fa-paper-plane mr-4" data-bs-toggle="tooltip"  title="Send this Post" style="float:right;"></i></p>
                <p class="card-text">
                <small class="text-muted">Published : <%= article.created_at.strftime(" %d  %B, %Y")%></small>
                <i class="" data-bs-toggle="tooltip"  title="View count" style="float:right; color:gray;"><%= link_to '' , my_article_view_article_path(article) , class:'fa-solid fa-chart-column mt-2 text-decoration-none' , style:"color:gray;" %></i><small style="float:right;" class="mr-1 mt-2"><%= article.article_views.count %></small>
                <i class="fa-solid fa-message mr-3 mt-2" data-bs-toggle="tooltip"  title="Comment count" style="float:right; color:gray;"></i><small style="float:right;" class="mr-1 mt-2">100</small>
                <i class="fa-solid fa-heart mr-3 mt-2" data-bs-toggle="tooltip"  title="Like count" style="float:right; color:gray;"></i><small style="float:right;" class="mr-1 mt-2"><%= article.likes.count %></small>
                </p>
            </div>
            </div>
        </div>
     </div>
    <% end %>
  </div>
  <div class="tab-pane fade" id="ex1-tabs-2" role="tabpanel" aria-labelledby="ex1-tab-2">
    <div class="card border shadow-none">
      <div class="text-center mt-5 mb-5">
        <span data-bs-toggle="tooltip" data-bs-placement="top" title="Total number of followers" class="mr-3 border-end pt-4 pb-4 pr-4" style="color:green;"><i class="fa-solid fa-users mr-3" style="color:gray;"></i> 2 Followers</span>
        <span data-bs-toggle="tooltip" data-bs-placement="top" title="Total number of posts" class="mr-3 border-end pt-4 pb-4 pr-4" style="color:green;"><i class="fa-regular fa-newspaper mr-2" style="color:gray;"></i> <%= @my_article.count %><%= link_to 'Posts' , my_article_article_path, class:'ml-1 text-decoration-none' , style:'color:green;'%></span>
        <span data-bs-toggle="tooltip" data-bs-placement="top" title="Total number of comments" class="pt-4 pb-4 pr-4" style="color:green;"><i class="fa-solid fa-comments mr-3" style="color:gray;"></i> 2 Comments</span>
      </div>
    </div>
  <div class="card border shadow-none mt-4">
      <div class="text-center mt-5 mb-5">
        <span class="mr-3 border-end pt-4 pb-4 pr-4" style="color:;">All time <b class="ml-2" style="font-size:18px;">100</b><i class="fa-solid fa-eye ml-2" style="color:#C6C6C6;"></i></span>
        <span class="mr-3 border-end pt-4 pb-4 pr-4" style="color:;">Today <b class="ml-2" style="font-size:18px;">100</b><i class="fa-solid fa-eye ml-2" style="color:#C6C6C6;"></i></span>
        <span class="mr-3 border-end pt-4 pb-4 pr-4" style="color:;">Yesterday <b class="ml-2" style="font-size:18px;">100</b><i class="fa-solid fa-eye ml-2" style="color:#C6C6C6;"></i></span>
        <span class="mr-3 border-end pt-4 pb-4 pr-4" style="color:;">This month <b class="ml-2" style="font-size:18px;">100</b><i class="fa-solid fa-eye ml-2" style="color:#C6C6C6;"></i></span>
        <span class="mr-3 border-end pt-4 pb-4 pr-4" style="color:;">Last month <b class="ml-2" style="font-size:18px;">100</b><i class="fa-solid fa-eye ml-2" style="color:#C6C6C6;"></i></span>
      </div>
  </div>
</div>
  <div class="tab-pane fade" id="ex1-tabs-3" role="tabpanel" aria-labelledby="ex1-tab-3">
    Tab 3 content
  </div>
  <div class="tab-pane fade" id="ex1-tabs-4" role="tabpanel" aria-labelledby="ex1-tab-4">
    Tab 4 content
  </div>
  <div class="tab-pane fade" id="ex1-tabs-5" role="tabpanel" aria-labelledby="ex1-tab-5">
    Tab 5 content
  </div>
  <div class="tab-pane fade" id="ex1-tabs-6" role="tabpanel" aria-labelledby="ex1-tab-6">
    Tab 6 content
  </div>
</div>
<!-- Tabs content -->
</div>
</div> 

</body>
</html> 
<script
  type="text/javascript"
  src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.3.1/mdb.min.js"
></script>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p><%= @article.content %></p>

<img  src=" <%= @article.file %> " style="width: 500px; height : 500px" class="rounded" alt="..." style="width: 500px; height: 500px;">


<p>Written by <%= @article.user.email %></p>

<% if current_user && current_user.likes.exists?(article_id: @article.id) %>
  <%= button_to 'Unlike', unlike_article_path(@article), method: :post %>
<% else %>
  <%= button_to 'Like', like_article_path(@article), method: :post %>
<% end %>

<% if user_signed_in? %>
  <% if current_user.bookmarks.exists?(article: @article) %>
    <%= button_to "Unbookmark", unbookmark_article_path(@article), method: :delete %>
  <% else %>
    <%= button_to "Bookmark", bookmark_article_path(@article), method: :post %>
  <% end %>
<% end %>

<p>Views: <%= @article.article_views.find_by(user: current_user)&.view_count || 0  %></p>

<%= link_to 'profile' , show_user_profile_profile_path(@article.user.profile.id) %>

<% if can? :update, @article %>
  <%= link_to "Edit", edit_article_path(@article) %> |
<% end %>

<%= render 'articles/star'%>
 

<%= link_to "Back", articles_path %>